---
driver:
  name: delegated
platforms:
  - name: instance-kind
provisioner:
  name: ansible
  log: true
  lint: {}
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    vvv: True
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - prepare
    - converge
    - verify
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
