---
- name: Check operation validation
  fail:
    msg: "Please provide operation as 'create' or 'delete'"
  when: operation not in ['create', 'delete']

- name: Check resource group name
  fail:
    msg: "Azure resource group must be defined as azure_resource_group"
  when: azure_resource_group is not defined

- block:
  - name: Check virtual network
    fail:
      msg: "Azure virtual network must be defined as azure_virtual_network"
    when: azure_virtual_network is not defined

  - name: Check subnet
    fail:
      msg: "Azure subnet must be defined as azure_subnet"
    when: azure_subnet is not defined

  - name: Check virtual network CIDR address prefixes
    fail:
      msg: "Azure virtual network CIDR address prefixes must be defined as azure_vnet_address_prefixes_cidr"
    when: azure_vnet_address_prefixes_cidr is not defined

  - name: Check subnet CIDR address prefixes
    fail:
      msg: "Azure subnet CIDR address prefixes must be defined as azure_subnet_address_prefixes_cidr"
    when: azure_subnet_address_prefixes_cidr is not defined

  when: operation == 'create'

- block:
  - name: Check delete option
    fail:
      msg: "Please provide delete_option as one of 'all', 'virtual_network', 'subnet'"
    when: delete_option not in ['all', 'virtual_network', 'subnet']

  - name: Check virtual network
    fail:
      msg: "Azure virtual network must be defined as azure_virtual_network"
    when:
    - operation in ['virtual_network', 'subnet']
    - azure_virtual_network is not defined

  - name: Check subnet
    fail:
      msg: "Azure subnet must be defined as azure_subnet"
    when:
    - operation == 'subnet'
    - azure_subnet is not defined

  when: operation == 'delete'

- include_tasks: "{{ operation }}.yml"
